In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import joblib as jb

In [93]:
data = pd.read_csv("premier_league.csv")

In [94]:
data.dropna(inplace=True)

In [95]:
football_data = data.copy()
del football_data['SourceFile']
football_data['Date'] = pd.to_datetime(football_data['Date'], errors='coerce')

/var/folders/fw/ff0yxbkj4png1_vbc9rxswcm0000gn/T/ipykernel_2193/696082657.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  football_data['Date'] = pd.to_datetime(football_data['Date'], errors='coerce')

In [96]:
all_teams = pd.concat([football_data['HomeTeam'], football_data['AwayTeam']])
team_encoder = LabelEncoder()
ref_encoder = LabelEncoder()
team_encoder.fit(all_teams)

football_data['HomeID'] = team_encoder.transform(football_data['HomeTeam'])
football_data['AwayID'] = team_encoder.transform(football_data['AwayTeam'])
football_data['RefereeID'] = ref_encoder.fit_transform(football_data['Referee'])


football_data['Month'] = football_data['Date'].dt.month
football_data['Year'] = football_data['Date'].dt.year

In [97]:
result_map = {'H': 1, 'D': 0, 'A': -1}
football_data['Result'] = football_data['FTR'].map(result_map)
football_data['HResult'] = football_data['HTR'].map(result_map)
football_data = football_data.sort_values("Date")

In [98]:
def calculate_team_form(df, team_name, match_date, N=5):
  
    past_matches = df[
        ((df['HomeTeam'] == team_name) | (df['AwayTeam'] == team_name)) &
        (df['Date'] < match_date)
    ].sort_values(by='Date', ascending=False).head(N)
    
    goals_scored = []
    goals_conceded = []
    results = []

    for _, row in past_matches.iterrows():
        if row['HomeTeam'] == team_name:
            goals_scored.append(row['FTHG'])
            goals_conceded.append(row['FTAG'])
            results.append(row['Result'])
        else:
            goals_scored.append(row['FTAG'])
            goals_conceded.append(row['FTHG'])
            results.append(-row['Result']) 


    if len(past_matches) == 0:
        return pd.Series([0, 0, 0])  
    
    avg_goals = np.mean(goals_scored)
    avg_conceded = np.mean(goals_conceded)
    win_rate = sum(1 for r in results if r == 1) / len(results)

    if ((df["Date"] == pd.to_datetime("2025-12-02")) & (df["HomeTeam"] == 'Everton')).any():
        print(goals_conceded, goals_scored, results)


    return pd.Series([avg_goals, avg_conceded, win_rate])

In [99]:
home_form_stats = football_data.apply(
    lambda row: calculate_team_form(football_data, row['HomeTeam'], row['Date']),
    axis=1
)

away_form_stats = football_data.apply(
    lambda row: calculate_team_form(football_data, row['AwayTeam'], row['Date']),
    axis=1
)

# Assign column names
home_form_stats.columns = ['HomeAvgGoals', 'HomeAvgConceded', 'HomeWinRate']
away_form_stats.columns = ['AwayAvgGoals', 'AwayAvgConceded', 'AwayWinRate']

# Merge into original dataset
football_data = pd.concat([football_data, home_form_stats, away_form_stats], axis=1)
football_data

[1] [0] [-1]
[3] [0] [-1]
[0] [0] [0]
[0] [1] [1]
[0] [3] [1]
[2] [0] [-1]
[1] [0] [-1]
[1] [0] [-1]
[1] [1] [0]
[3] [0] [-1]
[2] [1] [-1]
[3] [1] [-1]
[2] [1] [-1]
[2, 0] [1, 0] [-1, 0]
[0, 2, 0] [2, 1, 0] [1, -1, 0]
[1, 0, 1] [2, 2, 0] [1, 1, -1]
[1, 2] [2, 0] [1, -1]
[3, 3] [4, 1] [1, -1]
[3, 2] [2, 0] [-1, -1]
[2, 2] [1, 1] [-1, -1]
[0, 1, 0] [1, 3, 0] [1, 1, 0]
[0] [1] [1]
[4, 0, 3] [3, 3, 0] [-1, 1, -1]
[3, 1, 0] [2, 2, 3] [-1, 1, 1]
[0, 3] [2, 0] [1, -1]
[3, 0] [3, 1] [0, 1]
[2, 1, 2] [3, 2, 0] [1, 1, -1]
[1, 0, 3] [1, 2, 0] [0, 1, -1]
[2, 3, 1, 0] [2, 2, 2, 3] [0, -1, 1, 1]
[2, 2, 2] [0, 1, 1] [-1, -1, -1]
[0, 3, 0] [0, 3, 1] [0, 0, 1]
[1, 0, 2, 0] [1, 2, 1, 0] [0, 1, -1, 0]
[1, 4, 0, 3] [3, 3, 3, 0] [1, -1, 1, -1]
[1, 0, 1, 0] [2, 1, 3, 0] [1, 1, 1, 0]
[2, 3, 3] [1, 4, 1] [-1, 1, -1]
[0, 1, 0, 1] [6, 2, 2, 0] [1, 1, 1, -1]
[1, 2, 0, 0, 0] [0, 2, 1, 1, 1] [-1, 0, 1, 1, 1]
[3, 2, 2, 1] [1, 1, 1, 0] [-1, -1, -1, -1]
[1, 3, 1, 1] [3, 3, 0, 0] [1, 0, -1, -1]
[1, 6, 2, 1] [0, 0, 0, 2] [-1, -1, -1, 1]
[4, 1, 1, 2] [0, 2, 0, 1] [-1, 1, -1, -1]
[2, 1, 2, 1] [2, 1, 3, 0] [0, 0, 1, -1]
[2, 0, 1, 1] [0, 2, 2, 1] [-1, 1, 1, 0]
[2, 1, 3, 2] [0, 0, 2, 0] [-1, -1, -1, -1]
[4, 0, 1, 0] [2, 0, 1, 1] [-1, 0, 0, 1]
[1, 1, 3, 1, 1] [1, 3, 3, 0, 0] [0, 1, 0, -1, -1]
[2, 2, 0, 1, 1] [3, 0, 2, 2, 1] [1, -1, 1, 1, 0]
[2, 4, 1, 1, 2] [4, 0, 2, 0, 1] [1, -1, 1, -1, -1]
[1, 3, 2, 2, 1] [1, 1, 1, 1, 0] [0, -1, -1, -1, -1]
[0, 2, 1, 3, 2] [3, 0, 0, 2, 0] [1, -1, -1, -1, -1]
[0, 1, 6, 2, 1] [2, 0, 0, 0, 2] [1, -1, -1, -1, 1]
[0, 1, 2, 0, 0] [2, 0, 2, 1, 1] [1, -1, 0, 1, 1]
[2, 2, 1, 2, 1] [1, 2, 1, 3, 0] [-1, 0, 0, 1, -1]
[1, 4, 0, 1, 0] [0, 2, 0, 1, 1] [-1, -1, 0, 0, 1]
[0, 3, 0, 1] [0, 1, 1, 1] [0, -1, 1, 0]
[0, 2, 2, 0, 1] [2, 3, 0, 2, 2] [1, 1, -1, 1, 1]
[0, 0, 1, 6, 2] [0, 2, 0, 0, 0] [0, 1, -1, -1, -1]
[1, 1, 3, 2, 2] [2, 2, 1, 0, 1] [1, 1, -1, -1, -1]
[0, 1, 3, 2, 2] [1, 1, 1, 1, 1] [1, 0, -1, -1, -1]
[0, 0, 0, 1, 0] [0, 1, 0, 2, 1] [0, 1, 0, 1, 1]
[3, 2, 0, 1, 4] [3, 0, 1, 3, 3] [0, -1, 1, 1, -1]
[2, 1, 1, 3, 1] [1, 1, 3, 3, 0] [-1, 0, 1, 0, -1]
[2, 1, 0, 0, 1] [2, 1, 2, 6, 2] [0, 0, 1, 1, 1]
[5, 3, 0, 1, 0] [3, 0, 4, 1, 2] [-1, -1, 1, 0, 1]
[1, 3, 0, 1, 2] [1, 5, 2, 0, 2] [0, 1, 1, -1, 0]
[1, 0, 0, 1, 6] [1, 0, 2, 0, 0] [0, 0, 1, -1, -1]
[0, 1, 2, 2, 2] [0, 1, 0, 4, 2] [0, 0, -1, 1, 0]
[3, 2, 2, 4, 1] [2, 1, 4, 0, 2] [-1, -1, 1, -1, 1]
[1, 3, 2, 2, 1] [0, 3, 1, 2, 1] [-1, 0, -1, 0, 0]
[3, 1, 4, 0, 1] [0, 0, 2, 1, 1] [-1, -1, -1, 1, 0]
[2, 1, 4, 0, 1] [2, 0, 2, 0, 1] [0, -1, -1, 0, 0]
[1, 1, 1, 0, 3] [1, 2, 1, 0, 1] [0, 1, 0, 0, -1]
[3, 5, 3, 0, 1] [3, 3, 0, 4, 1] [0, -1, -1, 1, 0]
[5, 1, 2, 0, 2] [0, 2, 2, 3, 0] [-1, 1, 0, 1, -1]
[1, 0, 1, 0, 2] [0, 0, 2, 2, 1] [-1, 0, 1, 1, -1]
[0, 1, 3, 2, 2] [1, 0, 3, 1, 2] [1, -1, 0, -1, 0]
[0, 1, 3, 0, 1] [5, 1, 5, 2, 0] [1, 0, 1, 1, -1]
[0, 3, 1, 4, 0] [1, 0, 0, 2, 1] [1, -1, -1, -1, 1]
[1, 0, 1, 2, 2] [4, 0, 1, 0, 4] [1, 0, 0, -1, 1]
[0, 3, 2, 2, 4] [5, 2, 1, 4, 0] [1, -1, -1, 1, -1]
[1, 2, 1, 4, 0] [1, 2, 0, 2, 0] [0, 0, -1, -1, 0]
[2, 4, 2, 3, 2] [1, 1, 2, 2, 2] [-1, -1, 0, -1, 0]
[1, 2, 0, 1, 3] [2, 1, 1, 1, 1] [1, -1, 1, 0, -1]
[1, 2, 3, 2, 0] [1, 3, 3, 0, 1] [0, 1, 0, -1, 1]
[1, 3, 0, 2, 1] [3, 3, 3, 2, 1] [1, 0, 1, 0, 0]
[1, 1, 2, 2, 1] [1, 0, 1, 1, 1] [0, -1, -1, -1, 0]
[2, 5, 0, 0, 2] [0, 0, 0, 2, 3] [-1, -1, 0, 1, 1]
[1, 3, 2, 1, 1] [0, 3, 0, 1, 3] [-1, 0, -1, 0, 1]
[2, 3, 1, 0, 0] [0, 3, 1, 0, 2] [-1, 0, 0, 0, 1]
[2, 0, 1, 1, 3] [1, 0, 2, 2, 1] [-1, 0, 1, 1, -1]
[0, 0, 0, 0, 0] [2, 1, 0, 1, 0] [1, 1, 0, 1, 0]
[0, 0, 0, 1, 3] [1, 2, 1, 0, 3] [1, 1, 1, -1, 0]
[0, 1, 1, 2, 1] [3, 1, 1, 2, 0] [1, 0, 0, 0, -1]
[0, 0, 3, 5, 3] [1, 1, 3, 3, 0] [1, 1, 0, -1, -1]
[0, 1, 0, 3, 2] [0, 1, 5, 2, 1] [0, 0, 1, -1, -1]
[1, 0, 1, 1, 1] [1, 2, 1, 2, 1] [0, 1, 0, 1, 0]
[1, 3, 5, 1, 2] [1, 1, 0, 2, 2] [0, -1, -1, 1, 0]
[1, 2, 1, 0, 1] [1, 1, 0, 0, 2] [0, -1, -1, 0, 1]
[4, 1, 2, 4, 2] [1, 1, 1, 1, 2] [-1, 0, -1, -1, 0]
[1, 1, 2, 3, 2] [1, 1, 3, 3, 0] [0, 0, 1, 0, -1]
[2, 3, 2, 0, 1] [2, 0, 1, 0, 2] [0, -1, -1, 0, 1]
[1, 0, 1, 0, 3] [0, 0, 1, 5, 2] [-1, 0, 0, 1, -1]
[1, 1, 0, 3, 1] [1, 2, 1, 0, 0] [0, 1, 1, -1, -1]
[1, 1, 0, 0, 0] [0, 1, 2, 1, 0] [-1, 0, 1, 1, 0]
[3, 1, 2, 1, 0] [4, 1, 1, 0, 0] [1, 0, -1, -1, 0]
[0, 0, 1, 1, 2] [1, 3, 1, 2, 1] [1, 1, 0, 1, -1]
[3, 1, 3, 5, 1] [0, 1, 1, 0, 2] [-1, 0, -1, -1, 1]
[1, 1, 0, 1, 3] [1, 2, 5, 1, 5] [0, 1, 1, 0, 1]
[0, 2, 3, 2, 0] [1, 2, 0, 1, 0] [1, 0, -1, -1, 0]
[2, 4, 1, 2, 4] [2, 1, 1, 1, 1] [0, -1, 0, -1, -1]
[1, 1, 1, 1, 2] [3, 1, 1, 0, 1] [1, 0, 0, -1, -1]
[0, 1, 1, 1, 2] [4, 0, 1, 1, 3] [1, -1, 0, 0, 1]
[0, 3, 1, 3, 0] [3, 3, 3, 3, 3] [1, 0, 1, 0, 1]
[1, 0, 1, 2, 5] [3, 1, 0, 0, 0] [1, 1, -1, -1, -1]
[2, 4, 0, 1, 3] [1, 3, 0, 0, 3] [-1, -1, 0, -1, 0]
[2, 1, 1, 2, 3] [0, 1, 0, 0, 3] [-1, 0, -1, -1, 0]
[1, 1, 0, 1, 1] [1, 1, 3, 1, 1] [0, 0, 1, 0, 0]
[1, 3, 2, 1, 0] [0, 3, 0, 4, 0] [-1, 0, -1, 1, 0]
[3, 2, 2, 0, 0] [1, 2, 2, 1, 1] [-1, 0, 0, 1, 1]
[1, 1, 1, 0, 1] [0, 4, 1, 2, 1] [-1, 1, 0, 1, 0]
[1, 3, 0, 0, 0] [1, 1, 1, 2, 1] [0, -1, 1, 1, 1]
[1, 0, 1, 1, 0] [2, 1, 1, 2, 5] [1, 1, 0, 1, 1]
[0, 1, 1, 1, 0] [0, 0, 4, 1, 2] [0, -1, 1, 0, 1]
[1, 1, 3, 2, 1] [6, 0, 3, 0, 4] [1, -1, 0, -1, 1]
[0, 1, 0, 0, 1] [2, 1, 1, 3, 1] [1, 0, 1, 1, 0]
[1, 3, 1, 1, 0] [0, 0, 0, 1, 2] [-1, -1, -1, 0, 1]
[0, 0, 3, 1, 3] [3, 3, 3, 3, 3] [1, 1, 0, 1, 0]
[0, 0, 1, 1, 0] [0, 1, 1, 2, 1] [0, 1, 0, 1, 1]
[2, 1, 1, 0, 1] [1, 1, 1, 3, 1] [-1, 0, 0, 1, 0]
[2, 2, 1, 1, 2] [0, 0, 1, 0, 0] [-1, -1, 0, -1, -1]
[0, 0, 1, 1, 1] [1, 4, 0, 1, 1] [1, 1, -1, 0, 0]
[3, 1, 2, 4, 0] [0, 3, 1, 3, 0] [-1, 1, -1, -1, 0]
[1, 2, 2, 1, 1] [1, 0, 0, 1, 0] [0, -1, -1, 0, -1]
[1, 0, 1, 0, 0] [2, 2, 1, 1, 3] [1, 1, 0, 1, 1]
[1, 1, 3, 1, 1] [2, 0, 0, 0, 1] [1, -1, -1, -1, 0]
[0, 0, 0, 3, 1] [5, 3, 3, 3, 3] [1, 1, 1, 0, 1]
[0, 0, 0, 1, 1] [1, 0, 1, 1, 2] [1, 0, 1, 0, 1]
[1, 0, 2, 1, 1] [0, 1, 1, 1, 1] [-1, 1, -1, 0, 0]
[1, 0, 1, 1, 1] [2, 0, 0, 4, 1] [1, 0, -1, 1, 0]
[0, 1, 0, 1, 1] [5, 2, 1, 1, 2] [1, 1, 1, 0, 1]
[1, 3, 1, 3, 1] [1, 0, 3, 4, 1] [0, -1, 1, 1, 0]
[0, 2, 3, 4, 2] [0, 1, 1, 0, 2] [0, -1, -1, -1, 0]
[2, 2, 0, 3, 2] [0, 1, 1, 1, 2] [-1, -1, 1, -1, 0]
[4, 5, 0, 0, 1] [1, 0, 2, 2, 0] [-1, -1, 1, 1, -1]
[2, 2, 1, 3, 1] [1, 1, 0, 1, 3] [-1, -1, -1, -1, 1]
[1, 1, 1, 1, 0] [1, 0, 0, 3, 1] [0, -1, -1, 1, 1]
[2, 5, 2, 1, 3] [2, 0, 0, 1, 1] [0, -1, -1, 0, -1]
[0, 3, 0, 1, 3] [1, 1, 1, 1, 0] [1, -1, 1, 0, -1]
[2, 0, 3, 1, 2] [0, 1, 0, 3, 1] [-1, 1, -1, 1, -1]
[1, 6, 1, 0, 2] [0, 1, 2, 1, 2] [-1, -1, 1, 1, 0]
[0, 0, 2, 3, 4] [2, 0, 1, 1, 0] [1, 0, -1, -1, -1]
[0, 0, 3, 0, 1] [2, 1, 1, 1, 1] [1, 1, -1, 1, 0]
[1, 4, 5, 0, 0] [0, 1, 0, 2, 2] [-1, -1, -1, 1, 1]
[3, 2, 2, 1, 3] [0, 1, 1, 0, 1] [-1, -1, -1, -1, -1]
[0, 2, 5, 2, 1] [2, 2, 0, 0, 1] [1, 0, -1, -1, 0]
[1, 2, 0, 3, 1] [2, 0, 1, 0, 3] [1, -1, 1, -1, 1]
[0, 2, 2, 0, 3] [2, 0, 1, 1, 1] [1, -1, -1, 1, -1]
[1, 1, 6, 1, 0] [0, 0, 1, 2, 1] [-1, -1, -1, 1, 1]
[1, 1, 3, 1, 3] [0, 1, 0, 3, 4] [-1, 0, -1, 1, 1]
[2, 1, 1, 1, 1] [1, 1, 0, 0, 3] [-1, 0, -1, -1, 1]
[2, 2, 0, 1, 1] [1, 0, 3, 6, 0] [-1, -1, 1, 1, -1]
[2, 2, 1, 0, 0] [1, 1, 3, 1, 4] [-1, -1, 1, 1, 1]
[1, 2, 1, 1, 1] [2, 1, 1, 0, 0] [1, -1, 0, -1, -1]
[2, 3, 2, 2, 1] [2, 0, 1, 1, 0] [0, -1, -1, -1, -1]
[1, 0, 0, 3, 0] [2, 2, 1, 1, 1] [1, 1, 1, -1, 1]
[2, 0, 0, 1, 0] [3, 1, 2, 2, 2] [1, 1, 1, 1, 1]
[1, 0, 1, 1, 3] [1, 1, 0, 1, 0] [0, 1, -1, 0, -1]
[3, 0, 1, 1, 1] [0, 3, 1, 2, 0] [-1, 1, 0, 1, -1]
[1, 2, 0, 1, 0] [1, 0, 2, 2, 0] [0, -1, 1, 1, 0]
[3, 0, 0, 2, 3] [0, 2, 0, 1, 1] [-1, 1, 0, -1, -1]
[0, 0, 1, 0, 0] [3, 1, 2, 5, 3] [1, 1, 1, 1, 1]
[0, 1, 2, 0, 3] [3, 2, 0, 1, 0] [1, 1, -1, 1, -1]
[1, 4, 1, 1, 1] [0, 1, 1, 0, 0] [-1, -1, 0, -1, -1]
[1, 0, 0, 1, 0] [0, 3, 1, 2, 5] [-1, 1, 1, 1, 1]
[2, 0, 1, 2, 0] [0, 1, 2, 2, 1] [-1, 1, 1, 0, 1]
[1, 0, 1, 2, 0] [1, 3, 2, 0, 1] [0, 1, 1, -1, 1]
[3, 1, 0, 2, 2] [1, 0, 2, 0, 1] [-1, -1, 1, -1, -1]
[0, 1, 0, 1, 1] [2, 1, 1, 0, 1] [1, 0, 1, -1, 0]
[0, 1, 2, 2, 1] [1, 4, 1, 1, 3] [1, 1, -1, -1, 1]
[1, 3, 0, 1, 1] [3, 0, 3, 1, 2] [1, -1, 1, 0, 1]
[1, 1, 2, 2, 0] [0, 1, 1, 0, 3] [-1, 0, -1, -1, 1]
[0, 3, 0, 0, 2] [1, 0, 2, 0, 1] [1, -1, 1, 0, -1]
[0, 0, 2, 3, 2] [0, 1, 2, 0, 1] [0, 1, 0, -1, -1]
[4, 1, 1, 2, 0] [0, 1, 0, 0, 0] [-1, 0, -1, -1, 0]
[1, 2, 1, 2, 0] [2, 2, 1, 0, 2] [1, 0, 0, -1, 1]
[3, 2, 2, 2, 1] [0, 1, 2, 0, 0] [-1, -1, 0, -1, -1]
[1, 1, 1, 0, 0] [0, 1, 2, 2, 1] [-1, 0, 1, 1, 1]
[2, 1, 2, 0, 0] [0, 3, 3, 1, 2] [-1, 1, 1, 1, 1]
[1, 2, 3, 1, 4] [0, 2, 2, 0, 1] [-1, 0, -1, -1, -1]
[2, 1, 1, 2, 1] [0, 2, 2, 1, 1] [-1, 1, 1, -1, 0]
[2, 1, 2, 0, 1] [1, 1, 3, 1, 4] [-1, 0, 1, 1, 1]
[1, 3, 3, 0, 2] [1, 1, 2, 2, 2] [0, -1, -1, 1, 0]
[0, 1, 3, 3, 0] [2, 1, 1, 2, 2] [1, 0, -1, -1, 1]
[1, 2, 1, 1, 2] [2, 0, 2, 2, 1] [1, -1, 1, 1, -1]
[0, 0, 0, 2, 3] [1, 0, 1, 2, 0] [1, 0, 1, 0, -1]
[2, 2, 1, 2, 0] [2, 0, 3, 3, 1] [0, -1, 1, 1, 1]
[1, 4, 1, 1, 2] [6, 0, 1, 0, 0] [1, -1, 0, -1, -1]
[0, 1, 2, 3, 1] [0, 0, 2, 2, 0] [0, -1, 0, -1, -1]
[2, 0, 1, 1, 2] [2, 3, 0, 1, 1] [0, 1, -1, 0, -1]
[1, 5, 0, 3, 1] [4, 0, 1, 1, 0] [1, -1, 1, -1, -1]
[6, 1, 1, 3, 0] [1, 2, 3, 0, 3] [-1, 1, 1, -1, 1]
[2, 2, 0, 1, 0] [1, 1, 2, 1, 1] [-1, -1, 1, 0, 1]
[1, 0, 0, 0, 3] [0, 0, 2, 1, 0] [-1, 0, 1, 1, -1]
[1, 1, 1, 1, 4] [1, 2, 1, 0, 1] [0, 1, 0, -1, -1]
[2, 1, 0, 2, 0] [2, 4, 1, 0, 1] [0, 1, 1, -1, 1]
[1, 0, 0, 1, 2] [0, 4, 1, 4, 1] [-1, 1, 1, 1, -1]
[1, 0, 0, 1, 0] [1, 1, 2, 0, 3] [0, 1, 1, -1, 1]
[0, 1, 5, 0, 3] [1, 4, 0, 1, 1] [1, 1, -1, 1, -1]
[1, 1, 2, 1, 1] [1, 2, 0, 2, 2] [0, 1, -1, 1, 1]
[1, 4, 3, 2, 2] [2, 1, 0, 1, 2] [1, -1, -1, -1, 0]
[4, 0, 2, 2, 1] [1, 3, 2, 0, 3] [-1, 1, 0, -1, 1]
[0, 1, 0, 0, 0] [1, 0, 0, 2, 1] [1, -1, 0, 1, 1]
[0, 0, 1, 5, 0] [2, 1, 4, 0, 1] [1, 1, 1, -1, 1]
[1, 1, 1, 2, 1] [0, 0, 2, 2, 1] [-1, -1, 1, 0, 0]
[1, 1, 0, 0, 1] [3, 1, 1, 2, 0] [1, 0, 1, 1, -1]
[1, 2, 1, 0, 2] [4, 2, 4, 1, 0] [1, 0, 1, 1, -1]
[2, 1, 4, 3, 2] [0, 2, 1, 0, 1] [-1, 1, -1, -1, -1]
[0, 1, 2, 1, 4] [2, 0, 2, 6, 0] [1, -1, 0, 1, -1]
[1, 1, 1, 1, 2] [1, 1, 1, 2, 0] [0, 0, 0, 1, -1]
[1, 2, 1, 1, 1] [0, 1, 0, 1, 2] [-1, -1, -1, 0, 1]
[1, 4, 0, 1, 2] [1, 1, 0, 0, 2] [0, -1, 0, -1, 0]
[0, 1, 1, 0, 0] [1, 1, 1, 1, 0] [1, 0, 0, 1, 0]
[1, 2, 0, 0, 1] [1, 1, 1, 2, 1] [0, -1, 1, 1, 0]
[1, 3, 0, 2, 1] [0, 1, 5, 1, 1] [-1, -1, 1, -1, 0]
[2, 1, 1, 1, 2] [0, 0, 0, 2, 2] [-1, -1, -1, 1, 0]
[2, 4, 0, 2, 2] [0, 1, 3, 2, 0] [-1, -1, 1, 0, -1]
[4, 1, 0, 1, 0] [0, 0, 1, 0, 0] [-1, -1, 1, -1, 0]
[0, 3, 1, 1, 0] [3, 0, 3, 1, 1] [1, -1, 1, 0, 1]
[0, 3, 2, 0, 1] [0, 0, 0, 0, 1] [0, -1, -1, 0, 0]
[0, 0, 0, 1, 1] [3, 1, 2, 2, 0] [1, 1, 1, 1, -1]
[0, 1, 2, 2, 0] [4, 1, 1, 1, 2] [1, 0, -1, -1, 1]
[1, 0, 0, 2, 0] [1, 3, 1, 2, 3] [0, 1, 1, 0, 1]
[3, 1, 1, 1, 1] [1, 1, 1, 2, 1] [-1, 0, 0, 1, 0]
[2, 0, 2, 2, 6] [0, 2, 0, 1, 1] [-1, 1, -1, -1, -1]
[0, 0, 1, 2, 1] [2, 1, 4, 2, 4] [1, 1, 1, 0, 1]
[0, 1, 0, 0, 1] [0, 1, 2, 1, 4] [0, 0, 1, 1, 1]
[2, 3, 2, 1, 1] [0, 0, 0, 0, 0] [-1, -1, -1, -1, -1]
[1, 0, 1, 0, 0] [1, 0, 1, 2, 1] [0, 0, 0, 1, 1]
[0, 1, 0, 1, 2] [0, 1, 2, 0, 2] [0, 0, 1, -1, 0]
[1, 3, 0, 1, 2] [2, 1, 4, 1, 1] [1, -1, 1, 0, -1]
[1, 0, 1, 2, 1] [3, 0, 0, 1, 0] [1, 0, -1, -1, -1]
[1, 4, 1, 4, 0] [1, 0, 1, 1, 0] [0, -1, 0, -1, 0]
[0, 0, 1, 2, 0] [0, 0, 1, 1, 1] [0, 0, 0, -1, 1]
[0, 0, 0, 1, 2] [0, 2, 1, 4, 2] [0, 1, 1, 1, 0]
[1, 2, 1, 3, 0] [1, 0, 0, 1, 5] [0, -1, -1, -1, 1]
[1, 1, 0, 0, 2] [4, 1, 3, 1, 2] [1, 0, 1, 1, 0]
[0, 0, 0, 3, 2] [0, 0, 0, 0, 0] [0, 0, 0, -1, -1]
[0, 0, 0, 1, 2] [1, 0, 0, 1, 1] [1, 0, 0, 0, -1]
[2, 1, 0, 1, 2] [2, 3, 0, 0, 1] [0, 1, 0, -1, -1]
[0, 4, 0, 2, 4] [3, 1, 2, 0, 1] [1, -1, 1, -1, -1]
[2, 0, 0, 0, 3] [4, 0, 0, 0, 0] [1, 0, 0, 0, -1]
[4, 3, 1, 1, 1] [2, 1, 3, 3, 1] [-1, -1, 1, 1, 0]
[2, 0, 3, 2, 1] [0, 0, 0, 0, 2] [-1, 0, -1, -1, 1]
[1, 3, 3, 1, 1] [0, 1, 1, 1, 1] [-1, -1, -1, 0, 0]
[2, 1, 4, 1, 0] [1, 1, 0, 0, 1] [-1, 0, -1, -1, 1]
[2, 0, 0, 0, 1] [2, 0, 4, 1, 1] [0, 0, 1, 1, 0]
[1, 0, 2, 0, 2] [0, 0, 0, 2, 0] [-1, 0, -1, 1, -1]
[0, 0, 0, 3, 1] [1, 2, 3, 0, 3] [1, 1, 1, -1, 1]
[0, 1, 0, 2, 0] [2, 0, 0, 0, 2] [1, -1, 0, -1, 1]
[2, 1, 3, 3, 1] [2, 0, 1, 1, 1] [0, -1, -1, -1, 0]
[0, 2, 1, 4, 1] [1, 1, 1, 0, 0] [1, -1, 0, -1, -1]
[1, 2, 0, 0, 0] [0, 2, 0, 4, 1] [-1, 0, 0, 1, 1]
[1, 0, 0, 0, 3] [6, 1, 2, 3, 0] [1, 1, 1, 1, -1]
[1, 0, 0, 0, 0] [1, 0, 3, 1, 2] [0, 0, 1, 1, 1]
[0, 0, 4, 0, 2] [2, 3, 1, 2, 0] [1, 1, -1, 1, -1]
[2, 2, 0, 0, 0] [1, 4, 0, 0, 0] [-1, 1, 0, 0, 0]
[2, 2, 0, 3, 2] [1, 0, 0, 0, 0] [-1, -1, 0, -1, -1]
[1, 2, 1, 3, 3] [0, 2, 0, 1, 1] [-1, 0, -1, -1, -1]
[0, 0, 2, 1, 4] [1, 1, 1, 1, 0] [1, 1, -1, 0, -1]
[1, 0, 1, 0, 2] [2, 2, 0, 0, 0] [1, 1, -1, 0, -1]
[0, 6, 0, 0, 1] [1, 1, 2, 0, 1] [1, -1, 1, 0, 0]
[1, 0, 1, 1, 4] [1, 1, 1, 1, 0] [0, 1, 0, 0, -1]
[1, 1, 2, 0, 0] [1, 0, 2, 0, 4] [0, -1, 0, 0, 1]
[1, 2, 0, 2, 1] [0, 0, 2, 2, 3] [-1, -1, 1, 0, 1]
[1, 1, 0, 0, 1] [2, 2, 0, 1, 2] [1, 1, 0, 1, 1]
[0, 1, 0, 1, 0] [2, 2, 2, 0, 0] [1, 1, 1, -1, 0]
[0, 1, 1, 2, 0] [0, 1, 0, 2, 0] [0, 0, -1, 0, 0]
[1, 1, 4, 3, 1] [1, 0, 2, 1, 3] [0, -1, -1, -1, 1]
[0, 0, 2, 3, 0] [1, 1, 0, 0, 1] [1, 1, -1, -1, 1]
[3, 3, 1, 0, 1] [0, 0, 2, 0, 1] [-1, -1, 1, 0, 0]
[2, 0, 2, 2, 0] [1, 0, 1, 4, 0] [-1, 0, -1, 1, 0]
[2, 3, 3, 1, 0] [0, 0, 0, 2, 0] [-1, -1, -1, 1, 0]
[2, 2, 0, 2, 2] [3, 1, 0, 1, 4] [1, -1, 0, -1, 1]
[2, 0, 0, 2, 3] [1, 1, 1, 0, 0] [-1, 1, 1, -1, -1]
[0, 1, 1, 4, 3] [3, 1, 0, 2, 1] [1, 0, -1, -1, -1]
[0, 0, 2, 1, 1] [0, 0, 2, 2, 1] [0, 0, 0, 1, 0]
[0, 2, 1, 1, 1] [0, 1, 3, 4, 1] [0, -1, 1, 1, 0]
[3, 2, 2, 0, 3] [0, 1, 0, 0, 0] [-1, -1, -1, 0, -1]
[1, 0, 1, 0, 0] [1, 1, 6, 1, 2] [0, 1, 1, 1, 1]
[2, 0, 1, 0, 0] [0, 3, 1, 0, 3] [-1, 1, 0, 0, 1]
[3, 0, 1, 2, 2] [0, 3, 0, 1, 0] [-1, 1, -1, -1, -1]
[0, 0, 0, 6, 0] [0, 3, 1, 1, 2] [0, 1, 1, -1, 1]
[2, 3, 2, 2, 0] [2, 0, 1, 0, 0] [0, -1, -1, -1, 0]
[3, 0, 1, 2, 1] [0, 0, 0, 2, 0] [-1, 0, -1, 0, -1]
[1, 2, 0, 1, 0] [1, 0, 3, 1, 0] [0, -1, 1, 0, 0]
[2, 1, 1, 0, 1] [2, 0, 1, 1, 1] [0, -1, 0, 1, 0]
[2, 1, 1, 2, 1] [4, 0, 0, 0, 0] [1, -1, -1, -1, -1]
[1, 2, 3, 3, 1] [0, 0, 0, 0, 2] [-1, -1, -1, -1, 1]
[4, 0, 2, 1, 1] [2, 0, 1, 3, 4] [-1, 0, -1, 1, 1]
[0, 2, 0, 0, 4] [1, 1, 2, 3, 1] [1, -1, 1, 1, -1]
[1, 0, 3, 0, 1] [3, 0, 0, 3, 0] [1, 0, -1, 1, -1]
[0, 1, 1, 1, 1] [2, 2, 1, 2, 2] [1, 1, 0, 1, 1]
[0, 1, 2, 0, 1] [2, 1, 0, 3, 1] [1, 0, -1, 1, 0]
[1, 4, 0, 2, 1] [2, 2, 0, 1, 3] [1, -1, 0, -1, 1]
[0, 0, 0, 0, 6] [2, 0, 3, 1, 1] [1, 0, 1, 1, -1]
[1, 0, 1, 2, 0] [3, 2, 1, 0, 3] [1, 1, 0, -1, 1]
[3, 2, 2, 3, 2] [1, 2, 2, 0, 1] [-1, 0, 0, -1, -1]
[1, 1, 4, 0, 2] [2, 2, 2, 0, 1] [1, 1, -1, 0, -1]
[2, 2, 1, 1, 2] [0, 4, 0, 0, 0] [-1, 1, -1, -1, -1]
[2, 2, 0, 0, 1] [1, 0, 1, 2, 2] [-1, -1, 1, 1, 1]
[3, 2, 0, 1, 0] [1, 0, 2, 1, 1] [-1, -1, 1, 0, 1]
[2, 1, 0, 2, 0] [1, 3, 1, 1, 2] [-1, 1, 1, -1, 1]
[2, 1, 2, 3, 3] [0, 0, 0, 0, 0] [-1, -1, -1, -1, -1]
[1, 1, 0, 3, 0] [2, 3, 0, 0, 3] [1, 1, 0, -1, 1]
[4, 0, 0, 0, 0] [2, 2, 0, 3, 1] [-1, 1, 0, 1, 1]
[4, 0, 3, 0, 1] [2, 2, 0, 0, 0] [-1, 1, -1, 0, -1]
[3, 2, 1, 5, 1] [1, 0, 1, 1, 2] [-1, -1, 0, -1, 1]
[2, 0, 1, 2, 1] [1, 2, 0, 2, 1] [-1, 1, -1, 0, 0]
[0, 2, 1, 1, 0] [3, 1, 2, 5, 0] [1, -1, 1, 1, 0]
[1, 2, 2, 0, 1] [0, 2, 1, 3, 1] [-1, 0, -1, 1, 0]
[2, 2, 2, 0, 2] [3, 1, 0, 3, 3] [1, -1, -1, 1, 1]
[2, 2, 2, 0, 0] [0, 4, 1, 0, 0] [-1, 1, -1, 0, 0]
[2, 1, 2, 1, 2] [1, 3, 0, 0, 0] [-1, 1, -1, -1, -1]
[3, 1, 1, 1, 0] [3, 2, 2, 3, 0] [0, 1, 1, 1, 0]
[2, 3, 2, 0, 1] [4, 1, 0, 2, 1] [1, -1, -1, 1, 0]
[0, 3, 2, 2, 3] [2, 1, 2, 2, 0] [1, -1, 0, 0, -1]
[0, 0, 1, 1, 4] [3, 1, 2, 2, 2] [1, 1, 1, 1, -1]
[3, 4, 0, 0, 0] [0, 2, 2, 0, 3] [-1, -1, 1, 0, 1]
[1, 3, 2, 2, 1] [0, 2, 0, 4, 0] [-1, -1, -1, 1, -1]
[2, 2, 2, 2, 0] [0, 1, 1, 0, 1] [-1, -1, -1, -1, 1]
[1, 0, 2, 1, 0] [2, 1, 1, 3, 1] [1, 1, -1, 1, 1]
[2, 2, 1, 0, 1] [3, 1, 3, 2, 1] [1, -1, 1, 1, 0]
[0, 2, 0, 2, 1] [3, 1, 3, 1, 2] [1, -1, 1, -1, 1]
[0, 1, 0, 2, 0] [0, 0, 1, 1, 1] [0, -1, 1, -1, 1]
[3, 3, 2, 2, 2] [1, 0, 3, 1, 0] [-1, -1, 1, -1, -1]
[1, 1, 3, 2, 1] [1, 2, 1, 2, 0] [0, 1, -1, 0, -1]
[2, 0, 3, 2, 1] [0, 2, 1, 0, 1] [-1, 1, -1, -1, 0]
[4, 3, 2, 0, 1] [1, 2, 1, 2, 0] [-1, -1, -1, 1, -1]
[2, 0, 4, 0, 3] [0, 1, 2, 2, 0] [-1, 1, -1, 1, -1]
[0, 1, 1, 0, 1] [2, 2, 2, 2, 2] [1, 1, 1, 1, 1]
[1, 1, 1, 2, 2] [1, 2, 0, 2, 1] [0, 1, -1, 0, -1]
[0, 3, 2, 2, 2] [1, 3, 0, 4, 1] [1, 0, -1, 1, -1]
[0, 1, 1, 3, 2] [1, 1, 0, 2, 0] [1, 0, -1, -1, -1]
[0, 1, 2, 3, 2] [2, 1, 4, 1, 0] [1, 0, 1, -1, -1]
[1, 2, 2, 1, 2] [0, 0, 1, 3, 0] [-1, -1, -1, 1, -1]
[0, 1, 2, 2, 1] [2, 3, 3, 1, 3] [1, 1, 1, -1, 1]
[1, 3, 2, 2, 2] [0, 0, 0, 1, 1] [-1, -1, -1, -1, -1]
[2, 1, 0, 0, 1] [0, 0, 3, 1, 2] [-1, -1, 1, 1, 1]
[2, 0, 0, 3, 2] [1, 2, 2, 1, 2] [-1, 1, 1, -1, 0]
[1, 0, 0, 3, 1] [1, 0, 0, 3, 2] [0, 0, 0, 0, 1]
[1, 1, 3, 4, 0] [2, 4, 0, 2, 2] [1, 1, -1, -1, 1]
[1, 0, 1, 1, 3] [1, 1, 1, 0, 2] [0, 1, 0, -1, -1]
[1, 2, 1, 0, 0] [2, 0, 0, 3, 1] [1, -1, -1, 1, 1]
[0, 1, 2, 2, 1] [3, 0, 0, 1, 3] [1, -1, -1, -1, 1]
[2, 0, 0, 1, 1] [1, 2, 2, 2, 2] [-1, 1, 1, 1, 1]
[3, 1, 0, 1, 0] [0, 0, 0, 0, 1] [-1, -1, 0, -1, 1]
[3, 0, 1, 1, 1] [0, 1, 1, 2, 0] [-1, 1, 0, 1, -1]
[0, 3, 1, 0, 3] [1, 2, 2, 1, 3] [1, -1, 1, 1, 0]
[4, 0, 3, 3, 2] [2, 0, 1, 0, 3] [-1, 0, -1, -1, 1]
[2, 1, 4, 3, 2] [1, 2, 1, 2, 1] [-1, 1, -1, -1, -1]
[0, 2, 2, 0, 3] [1, 1, 0, 2, 1] [1, -1, -1, 1, -1]
[3, 2, 2, 0, 4] [2, 0, 0, 1, 2] [-1, -1, -1, 1, -1]
[1, 3, 1, 0, 1] [2, 0, 0, 0, 0] [1, -1, -1, 0, -1]
[0, 3, 0, 1, 1] [0, 0, 1, 1, 2] [0, -1, 1, 0, 1]
[1, 2, 0, 2, 0] [1, 0, 3, 1, 3] [0, -1, 1, -1, 1]
[0, 1, 1, 3, 2] [1, 1, 2, 1, 2] [1, 0, 1, -1, 0]
[1, 2, 0, 0, 1] [6, 1, 2, 2, 2] [1, -1, 1, 1, 1]
[2, 2, 1, 4, 3] [2, 1, 2, 1, 2] [0, -1, 1, -1, -1]
[2, 1, 0, 1, 2] [1, 1, 3, 0, 0] [-1, 0, 1, -1, -1]
[3, 2, 1, 3, 2] [1, 4, 0, 0, 0] [-1, 1, -1, -1, -1]
[2, 1, 1, 2, 0] [2, 3, 6, 1, 2] [0, 1, 1, -1, 1]
[1, 0, 2, 2, 0] [1, 1, 1, 0, 2] [0, 1, -1, -1, 1]
[3, 1, 2, 1, 0] [0, 1, 3, 1, 0] [-1, 0, 1, 0, 0]
[1, 2, 0, 1, 0] [1, 1, 2, 2, 1] [0, -1, 1, 1, 1]
[2, 2, 2, 1, 4] [2, 2, 1, 2, 1] [0, 0, -1, 1, -1]
[0, 0, 0, 1, 2] [4, 3, 2, 3, 3] [1, 1, 1, 1, 1]
[0, 2, 1, 1, 2] [2, 2, 3, 6, 1] [1, 0, 1, 1, -1]
[4, 1, 0, 2, 2] [0, 1, 1, 1, 0] [-1, 0, 1, -1, -1]
[2, 0, 0, 1, 1] [2, 4, 2, 2, 0] [0, 1, 1, 1, -1]
[2, 0, 0, 0, 1] [2, 4, 3, 2, 3] [0, 1, 1, 1, 1]
[3, 3, 2, 1, 3] [1, 1, 4, 0, 0] [-1, -1, 1, -1, -1]
[3, 2, 1, 0, 1] [1, 1, 0, 2, 1] [-1, -1, -1, 1, 0]
[2, 2, 1, 0, 1] [2, 3, 1, 1, 1] [0, 1, 0, 1, 0]
[1, 1, 2, 0, 2] [2, 1, 0, 3, 1] [1, 0, -1, 1, -1]
[1, 3, 3, 2, 1] [1, 1, 1, 4, 0] [0, -1, -1, 1, -1]
[0, 0] [2, 0] [1, 0]
[1, 3, 2, 1, 0] [4, 1, 1, 0, 2] [1, -1, -1, -1, 1]
[0, 4, 1, 0, 2] [0, 0, 1, 1, 1] [0, -1, 0, 1, -1]
[4, 0, 3, 1, 0] [0, 1, 2, 2, 1] [-1, 1, -1, 1, 1]
[3, 2, 0, 0, 0] [1, 2, 4, 3, 2] [-1, 0, 1, 1, 1]
[1, 4, 0, 3, 1] [3, 0, 1, 2, 2] [1, -1, 1, -1, 1]
[0, 2, 2, 1, 0] [1, 2, 3, 1, 1] [1, 0, 1, 0, 1]
[2, 4, 1, 1, 2] [0, 1, 2, 1, 0] [-1, -1, 1, 0, -1]
[3, 1, 4, 0, 3] [1, 3, 2, 0, 1] [-1, 1, -1, 0, -1]
[4, 1, 3, 3, 2] [0, 1, 1, 1, 4] [-1, 0, -1, -1, 1]
[0, 0, 2, 1, 1] [0, 2, 2, 3, 6] [0, 1, 0, 1, 1]
[0, 0, 4, 1, 0] [1, 0, 0, 1, 1] [1, 0, -1, 0, 1]
[0, 3, 2, 0, 0] [2, 1, 2, 4, 3] [1, -1, 0, 1, 1]
[1, 2, 0, 0, 1] [1, 2, 4, 2, 2] [0, 0, 1, 1, 1]
[1, 1, 3, 2, 1] [0, 4, 1, 1, 0] [-1, 1, -1, -1, -1]
[1, 2, 4, 1, 2] [2, 0, 1, 3, 2] [1, -1, -1, 1, 0]
[0, 1, 3, 0, 1] [4, 1, 2, 0, 2] [1, 0, -1, 0, 1]
[0, 1, 0, 3, 2] [5, 0, 0, 2, 2] [1, -1, 0, -1, 0]
[1, 1, 1, 1, 2] [0, 1, 2, 1, 1] [-1, 0, 1, 0, -1]
[3, 0, 0, 0] [2, 2, 2, 0] [-1, 1, 1, 0]
[2, 1, 1, 1] [1, 0, 2, 0] [-1, -1, 1, -1]
[2, 0, 1, 3, 0] [1, 4, 1, 2, 0] [-1, 1, 0, -1, 0]
[2, 2, 1, 1, 1] [2, 1, 0, 2, 0] [0, -1, -1, 1, -1]
[0, 3, 0, 0, 0] [2, 2, 2, 2, 0] [1, -1, 1, 1, 0]
[1, 1, 1, 1, 1] [3, 0, 1, 2, 1] [1, -1, 0, 1, 0]
[2, 0, 2, 2, 1] [0, 4, 0, 3, 2] [-1, 1, -1, 1, 1]
[2, 0, 0, 2, 2] [1, 1, 0, 2, 0] [-1, 1, 0, 0, -1]
[1, 1, 2, 4, 1] [1, 2, 0, 1, 3] [0, 1, -1, -1, 1]
[0, 1, 2, 3, 1] [0, 3, 2, 0, 1] [0, 1, 0, -1, 0]
[1, 1, 0, 0, 3] [1, 4, 3, 0, 0] [0, 1, 1, 0, -1]
[0, 0, 1, 0, 3] [1, 5, 0, 0, 2] [1, 1, -1, 0, -1]
[2, 1, 4, 2, 4] [0, 0, 0, 0, 1] [-1, -1, -1, -1, -1]
[0, 2, 1, 4, 0] [1, 1, 3, 0, 1] [1, -1, 1, -1, 1]
[2, 1, 0, 3, 1] [1, 1, 0, 1, 3] [-1, 0, 0, -1, 1]
[1, 2, 2, 1, 1] [2, 2, 1, 0, 2] [1, 0, -1, -1, 1]
[0, 1, 2, 0, 0] [0, 1, 0, 1, 1] [0, 0, -1, 1, 1]
[0, 2, 0, 1, 3] [4, 1, 4, 1, 2] [1, -1, 1, 0, -1]

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,Month,Year,Result,HResult,HomeAvgGoals,HomeAvgConceded,HomeWinRate,AwayAvgGoals,AwayAvgConceded,AwayWinRate
10329,2000-01-10,Arsenal,Man United,1,0,H,1.0,0.0,H,Graham Barber,...,1,2000,1,1,0.0,0.0,0.0,0.0,0.0,0.0
10331,2000-01-10,Sunderland,Leicester,0,0,D,0.0,0.0,D,Steve Lodge,...,1,2000,0,0,0.0,0.0,0.0,0.0,0.0,0.0
10330,2000-01-10,Chelsea,Liverpool,3,0,H,2.0,0.0,H,Dermot Gallagher,...,1,2000,1,1,0.0,0.0,0.0,0.0,0.0,0.0
10409,2000-02-12,West Ham,Middlesbrough,1,0,H,1.0,0.0,H,Roy Burton,...,2,2000,1,1,0.0,0.0,0.0,0.0,0.0,0.0
10408,2000-02-12,Man United,Tottenham,2,0,H,1.0,0.0,H,Graham Poll,...,2,2000,1,1,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6335,2026-11-02,Crystal Palace,Burnley,2,3,A,2.0,3.0,A,F Hallam,...,11,2026,-1,-1,1.0,0.6,0.6,1.0,2.4,0.0
6336,2026-11-02,Man City,Fulham,3,0,H,3.0,0.0,H,P Tierney,...,11,2026,1,1,1.4,1.0,0.4,1.6,1.4,0.4
6338,2026-11-02,Sunderland,Liverpool,0,1,A,0.0,0.0,D,C Kavanagh,...,11,2026,-1,0,0.6,1.6,0.2,1.8,1.6,0.2
6337,2026-11-02,Nott'm Forest,Wolves,0,0,D,0.0,0.0,D,T Robinson,...,11,2026,0,0,1.2,2.0,0.2,1.8,1.0,0.6
6339,2026-12-02,Brentford,Arsenal,1,1,D,0.0,0.0,D,J Brooks,...,12,2026,0,0,2.8,1.4,0.8,2.2,0.6,0.8

In [100]:
corr_matrix = football_data.copy()
corr_matrix.drop(columns=corr_matrix.select_dtypes(exclude=[np.number]).columns, inplace=True)
corr_matrix.corr()['Result']

FTHG               0.630430
FTAG              -0.633986
HTHG               0.431949
HTAG              -0.421580
HS                 0.221618
AS                -0.253809
HST                0.323476
AST               -0.320249
HF                -0.034816
AF                 0.034405
HC                 0.052635
AC                -0.045274
HY                -0.117096
AY                 0.032544
HR                -0.129283
AR                 0.094448
HomeID            -0.061935
AwayID             0.070149
RefereeID          0.022694
Month             -0.026143
Year              -0.040402
Result             1.000000
HResult            0.594564
HomeAvgGoals       0.169809
HomeAvgConceded   -0.146971
HomeWinRate        0.172757
AwayAvgGoals      -0.181526
AwayAvgConceded    0.121084
AwayWinRate       -0.174477
Name: Result, dtype: float64

In [101]:
from sklearn.ensemble import RandomForestClassifier

In [102]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [103]:
train = football_data[football_data["Date"] < '2024-01-01']
test = football_data[football_data["Date"] > '2024-01-01']

In [104]:
# predictors = ["HomeID", "AwayID", "HResult", "RefereeID", "Month", "Year","FTHG","HTHG","AR","AY","HC","AF","HST","HS"]
# predictors = ["HomeID", "AwayID", "RefereeID", "Month", "Year"]
# predictors = [
#     "HomeID", "AwayID", "RefereeID", "Month", "Year",
#     "HomeAvgGoals", "HomeAvgConceded", "HomeWinRate",
#     "AwayAvgGoals", "AwayAvgConceded", "AwayWinRate",
# ]
predictors = [
    "HomeID", "AwayID", "RefereeID", "Month", "Year",
 "HomeWinRate","AwayWinRate",
]

In [105]:
rf.fit(train[predictors], train["Result"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [106]:
preds = rf.predict(test[predictors])

In [107]:
from sklearn.metrics import accuracy_score

In [108]:
acc = accuracy_score(test["Result"], preds)

In [109]:
acc

0.4894613583138173

In [110]:
combine = pd.DataFrame(dict(actual=test["Result"], prediction=preds))

In [111]:
pd.crosstab(index=combine["actual"], columns=combine["prediction"])

prediction   -1   0    1
actual
-1          112  16  153
 0           60  10  145
 1           52  10  296

In [112]:
def predict_match_with_form(home_team, away_team, referee, match_date_str):
    match_date = pd.to_datetime(match_date_str)
    
    try:
        home_id = team_encoder.transform([home_team])[0]
        away_id = team_encoder.transform([away_team])[0]
    except ValueError:
        print("❗ Unknown team name.")
        return
    
    referee_id = (
        ref_encoder.transform([referee])[0]
        if referee in ref_encoder.classes_
        else -1
    )
    
    home_form = calculate_team_form(football_data, home_team, match_date)
    away_form = calculate_team_form(football_data, away_team, match_date)

    row = pd.DataFrame([{
        "HomeID": home_id,
        "AwayID": away_id,
        "RefereeID": referee_id,
        "Month": match_date.month,
        "Year": match_date.year,
        "HomeAvgGoals": home_form[0],
        "HomeAvgConceded": home_form[1],
        "HomeWinRate": home_form[2],
        "AwayAvgGoals": away_form[0],
        "AwayAvgConceded": away_form[1],
        "AwayWinRate": away_form[2],
    }])
    
    pred = rf.predict(row)[0]
    result_map = {1: "🏠 Home Win", 0: "🤝 Draw", -1: "✈️ Away Win"}
    
    print(f"🔮 Prediction for {home_team} vs {away_team} on {match_date.date()}: {result_map[pred]}")

In [113]:
predict_match_with_form("Arsenal", "Liverpool", "T Robinson", "2026-06-07")

[0, 2, 1, 2, 0] [1, 3, 4, 2, 4] [1, 1, 1, 0, 1]
[2, 2, 2, 0, 1] [2, 1, 5, 1, 4] [0, -1, 1, 1, 1]

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- AwayAvgConceded
- AwayAvgGoals
- HomeAvgConceded
- HomeAvgGoals

In [ ]:
jb.dump(rf, "model.pkl")
jb.dump(team_encoder, "team_encoder.pkl")
jb.dump(ref_encoder, "ref_encoder.pkl")

['ref_encoder.pkl']